### ISSUE TITLE
Multiple paragraphs in blockquote

### ISSUE THREAD

**Issue by jensscherbl** [hgilani/html2markdown#1]
When converting blockquotes with multiple paragraps, only the first paragraph is converted properly.

(By the way, great work so far!)

**Comment by hgilani** [comment]
Thanks for the compliment. Could you give sample HTML or link to any public page where I can reproduce this issue.

**Comment by jensscherbl** [comment]
Sure, thanks for looking into it.

```
<blockquote>
    <p>Lorem ipsum</p>
    <p>Lorem ipsum</p>
</blockquote>
```

and

```
<blockquote>
    <p>Lorem Ipsum</p>
</blockquote>
<blockquote>
    <p>Lorem Ipsum</p>
</blockquote>
```

both don't convert very well.

**Comment by hgilani** [comment]
Fixed. This should convert now as 

```
> Lorem ipsum

> Lorem ipsum

```
